import { Translations } from '@/types';

export const translations: Translations = {
  // Navigation
  'nav.dashboard': { az: 'İdarə paneli', en: 'Dashboard', tr: 'Kontrol Paneli' },
  'nav.analyze': { az: 'Təhlil', en: 'Analyze', tr: 'Analiz' },
  'nav.reports': { az: 'Hesabatlar', en: 'Reports', tr: 'Raporlar' },
  'nav.settings': { az: 'Tənzimləmələr', en: 'Settings', tr: 'Ayarlar' },
  
  // Landing Page
  'hero.title': { 
    az: 'PhishScope Pro - Peşəkar Kibertəhlükəsizlik Platforması', 
    en: 'PhishScope Pro - Advanced Cybersecurity Platform',
    tr: 'PhishScope Pro - Gelişmiş Siber Güvenlik Platformu' 
  },
  'hero.subtitle': { 
    az: 'SOC komandaları və təhlükəsizlik analitikləri üçün AI əsaslı phishing email təhlili', 
    en: 'AI-powered phishing email analysis for SOC teams and security analysts',
    tr: 'SOC ekipleri ve güvenlik analistleri için yapay zeka destekli phishing e-posta analizi' 
  },
  'hero.cta': { az: 'Pulsuz başla', en: 'Start Free Trial', tr: 'Ücretsiz Başla' },
  
  // Features
  'features.email_parsing': { az: 'Email Təhlili', en: 'Email Parsing', tr: 'E-posta Analizi' },
  'features.auth_validation': { az: 'Autentifikasiya Yoxlaması', en: 'Authentication Validation', tr: 'Kimlik Doğrulama Doğrulaması' },
  'features.osint_enrichment': { az: 'OSINT Zənginləşdirmə', en: 'OSINT Enrichment', tr: 'OSINT Zenginleştirme' },
  'features.ai_attribution': { az: 'AI Təhdid Atributu', en: 'AI Threat Attribution', tr: 'Yapay Zeka Tehdit Ataması' },
  
  // Analysis
  'analysis.upload_email': { az: 'Email yüklə', en: 'Upload Email', tr: 'E-posta Yükle' },
  'analysis.threat_score': { az: 'Təhdid səviyyəsi', en: 'Threat Score', tr: 'Tehdit Skoru' },
  'analysis.processing': { az: 'İşlənir...', en: 'Processing...', tr: 'İşleniyor...' },
  'analysis.completed': { az: 'Tamamlandı', en: 'Completed', tr: 'Tamamlandı' },
  
  // Pricing
  'pricing.free': { az: 'Pulsuz', en: 'Free', tr: 'Ücretsiz' },
  'pricing.pro': { az: 'Peşəkar', en: 'Pro', tr: 'Pro' },
  'pricing.team': { az: 'Komanda', en: 'Team', tr: 'Takım' },
  'pricing.enterprise': { az: 'Müəssisə', en: 'Enterprise', tr: 'Kurumsal' },
  
  // Common
  'common.loading': { az: 'Yüklənir...', en: 'Loading...', tr: 'Yükleniyor...' },
  'common.error': { az: 'Xəta', en: 'Error', tr: 'Hata' },
  'common.success': { az: 'Uğurlu', en: 'Success', tr: 'Başarılı' },
  'common.cancel': { az: 'Ləğv et', en: 'Cancel', tr: 'İptal' },
  'common.save': { az: 'Saxla', en: 'Save', tr: 'Kaydet' },
  'common.delete': { az: 'Sil', en: 'Delete', tr: 'Sil' },
  'common.export': { az: 'İxrac et', en: 'Export', tr: 'Dışa Aktar' },
  'common.view': { az: 'Bax', en: 'View', tr: 'Görüntüle' },
  
  // Footer
  'footer.product': { az: 'Məhsul', en: 'Product', tr: 'Ürün' },
  'footer.company': { az: 'Şirkət', en: 'Company', tr: 'Şirket' },
  'footer.support': { az: 'Dəstək', en: 'Support', tr: 'Destek' },
  'footer.legal': { az: 'Hüquqi', en: 'Legal', tr: 'Yasal' },
  'footer.documentation': { az: 'Sənədləşmə', en: 'Documentation', tr: 'Dokümantasyon' },
  'footer.careers': { az: 'Karyera', en: 'Careers', tr: 'Kariyer' },
  'footer.contact': { az: 'Əlaqə', en: 'Contact', tr: 'İletişim' },
  'footer.status': { az: 'Status', en: 'Status', tr: 'Durum' },
  'footer.blog': { az: 'Bloq', en: 'Blog', tr: 'Blog' },
  'footer.helpcenter': { az: 'Yardım Mərkəzi', en: 'Help Center', tr: 'Yardım Merkezi' },
  'footer.technicalsupport': { az: 'Texniki Dəstək', en: 'Technical Support', tr: 'Teknik Destek' },
  'footer.training': { az: 'Təlim', en: 'Training', tr: 'Eğitim' },
  'footer.community': { az: 'İcma', en: 'Community', tr: 'Topluluk' },
  'footer.security': { az: 'Təhlükəsizlik', en: 'Security', tr: 'Güvenlik' },
  'footer.terms': { az: 'Şərtlər', en: 'Terms', tr: 'Şartlar' },
  'footer.privacy': { az: 'Gizlilik', en: 'Privacy', tr: 'Gizlilik' },
  'footer.cookies': { az: 'Kukilər', en: 'Cookies', tr: 'Çerezler' },
  'footer.license': { az: 'Lisenziya', en: 'License', tr: 'Lisans' },
  'footer.gdpr': { az: 'GDPR', en: 'GDPR', tr: 'GDPR' },
  'footer.language': { az: 'Dil', en: 'Language', tr: 'Dil' },
  'footer.rights': { az: 'Bütün hüquqlar qorunur.', en: 'All rights reserved.', tr: 'Tüm hakları saklıdır.' },
  'footer.termsofservice': { az: 'Xidmət şərtləri', en: 'Terms of Service', tr: 'Hizmet Şartları' },
  'footer.privacypolicy': { az: 'Gizlilik siyasəti', en: 'Privacy Policy', tr: 'Gizlilik Politikası' },
  'footer.cookiepolicy': { az: 'Kuki siyasəti', en: 'Cookie Policy', tr: 'Çerez Politikası' },

  // OSINT
  'osint.results': { az: 'Nəticələr', en: 'Results', tr: 'Sonuçlar' },
  'osint.ips': { az: 'IP-lər', en: 'IPs', tr: 'IPler' },
  'osint.domains': { az: 'Domenlər', en: 'Domains', tr: 'Alan Adları' },
  'osint.urls': { az: 'URL-lər', en: 'URLs', tr: 'URLler' },
  'osint.noIpData': { az: 'IP məlumatı yoxdur', en: 'No IP data', tr: 'IP verisi yok' },
  'osint.malicious': { az: 'Zərərli', en: 'Malicious', tr: 'Zararlı' },
  'osint.clean': { az: 'Təmiz', en: 'Clean', tr: 'Temiz' },
  'osint.confidence': { az: 'Etibarlılıq', en: 'Confidence', tr: 'Güven' },
  'osint.reports': { az: 'Hesabatlar', en: 'Reports', tr: 'Raporlar' },
  'osint.noDomainData': { az: 'Domen məlumatı yoxdur', en: 'No domain data', tr: 'Alan adı verisi yok' },
  'osint.suspicious': { az: 'Şübhəli', en: 'Suspicious', tr: 'Şüpheli' },
  'osint.created': { az: 'Yaradılma tarixi', en: 'Created', tr: 'Oluşturulma' },
  'osint.registrar': { az: 'Qeydiyyatçı', en: 'Registrar', tr: 'Kayıt Eden' },
  'osint.noUrlData': { az: 'URL məlumatı yoxdur', en: 'No URL data', tr: 'URL verisi yok' },
  'osint.threats': { az: 'Təhlükələr', en: 'Threats', tr: 'Tehditler' },
  'osint.categories': { az: 'Kateqoriyalar', en: 'Categories', tr: 'Kategoriler' },
  'osint.screenshot': { az: 'Ekran görüntüsü', en: 'Screenshot', tr: 'Ekran Görüntüsü' },

  // File Upload
  'fileupload.dropHere': { az: 'Buraya atın', en: 'Drop here', tr: 'Buraya bırakın' },
  'fileupload.uploadFile': { az: 'Fayl yüklə', en: 'Upload file', tr: 'Dosya yükle' },
  'fileupload.fileDescription': { az: 'Fayl təsviri', en: 'File description', tr: 'Dosya açıklaması' },
  'fileupload.maxSize': { az: 'Maksimum ölçü', en: 'Max size', tr: 'Maksimum boyut' },
  'fileupload.fileTooLarge': { az: 'Fayl çox böyükdür', en: 'File is too large', tr: 'Dosya çok büyük' },
  'fileupload.unsupportedFormat': { az: 'Dəstəklənməyən format', en: 'Unsupported format', tr: 'Desteklenmeyen format' },

  // Threat Score
  'threatscore.high': { az: 'Yüksək', en: 'High', tr: 'Yüksek' },
  'threatscore.medium': { az: 'Orta', en: 'Medium', tr: 'Orta' },
  'threatscore.low': { az: 'Aşağı', en: 'Low', tr: 'Düşük' },
  'threatscore.safe': { az: 'Təhlükəsiz', en: 'Safe', tr: 'Güvenli' },
  'threatscore.label': { az: 'Təhdid səviyyəsi', en: 'Threat Score', tr: 'Tehdit Skoru' },
  'threatscore.confidence': { az: 'Etibarlılıq', en: 'Confidence', tr: 'Güven' },

  // Premium
  'premium.feature': { az: 'Premium xüsusiyyət', en: 'Premium feature', tr: 'Premium özellik' },
  'premium.paidRequired': { az: 'Ödəniş tələb olunur', en: 'Payment required', tr: 'Ödeme gerekli' },
  'premium.trialExpired': { az: 'Sınaq müddəti bitdi', en: 'Trial expired', tr: 'Deneme süresi doldu' },
  'premium.limitedAccess': { az: 'Məhdud giriş', en: 'Limited access', tr: 'Sınırlı erişim' },
  'premium.viewPlans': { az: 'Planlara bax', en: 'View plans', tr: 'Planları Görüntüle' },
  'premium.backToDashboard': { az: 'Panelə qayıt', en: 'Back to dashboard', tr: "Panel'e Dön" },

  // Auth
  'auth.logout': { az: 'Çıxış', en: 'Logout', tr: 'Çıkış Yap' },
  'auth.signin': { az: 'Daxil ol', en: 'Sign in', tr: 'Giriş Yap' },
  'auth.signup': { az: 'Qeydiyyat', en: 'Sign up', tr: 'Kayıt Ol' },

  // Demo & API
  'demo': { az: 'Demo', en: 'Demo', tr: 'Demo' },
  'api': { az: 'API', en: 'API', tr: 'API' },

  // Terms (placeholders)
  'terms.serviceDescription': { az: 'Xidmət təsviri', en: 'Service Description', tr: 'Hizmet Açıklaması' },
  'terms.serviceDescriptionContent': { az: 'Xidmət təsviri məzmunu', en: 'Service description content', tr: 'Hizmet açıklaması içeriği' },
  'terms.usageTerms': { az: 'İstifadə şərtləri', en: 'Usage Terms', tr: 'Kullanım Şartları' },
  'terms.usageTermsContent': { az: 'İstifadə şərtləri məzmunu', en: 'Usage terms content', tr: 'Kullanım şartları içeriği' },
  'terms.paymentTerms': { az: 'Ödəniş şərtləri', en: 'Payment Terms', tr: 'Ödeme Şartları' },
  'terms.paymentTermsContent': { az: 'Ödəniş şərtləri məzmunu', en: 'Payment terms content', tr: 'Ödeme şartları içeriği' },
  'terms.liabilityLimitations': { az: 'Məsuliyyət məhdudiyyətləri', en: 'Liability Limitations', tr: 'Sorumluluk Sınırlamaları' },
  'terms.liabilityLimitationsContent': { az: 'Məsuliyyət məhdudiyyətləri məzmunu', en: 'Liability limitations content', tr: 'Sorumluluk sınırlamaları içeriği' },
  'terms.userResponsibilities': { az: 'İstifadəçi öhdəlikləri', en: 'User Responsibilities', tr: 'Kullanıcı Sorumlulukları' },
  'terms.userResponsibilitiesContent': { az: 'İstifadəçi öhdəlikləri məzmunu', en: 'User responsibilities content', tr: 'Kullanıcı sorumlulukları içeriği' },
  'terms.serviceSuspension': { az: 'Xidmətin dayandırılması', en: 'Service Suspension', tr: 'Hizmetin Askıya Alınması' },
  'terms.serviceSuspensionContent': { az: 'Xidmətin dayandırılması məzmunu', en: 'Service suspension content', tr: 'Hizmetin askıya alınması içeriği' },
  'terms.termsOfService': { az: 'Xidmət şərtləri', en: 'Terms of Service', tr: 'Hizmet Şartları' },
  'terms.serviceTerms': { az: 'Xidmət şərtləri', en: 'Service Terms', tr: 'Hizmet Şartları' },
  'terms.termsOfServiceDescription': { az: 'Xidmət şərtləri təsviri', en: 'Terms of service description', tr: 'Hizmet şartları açıklaması' },
  'terms.lastUpdated': { az: 'Son yeniləmə', en: 'Last updated', tr: 'Son Güncelleme' },
  'terms.importantNotice': { az: 'Vacib Qeyd', en: 'Important Notice', tr: 'Önemli Not' },
  'terms.importantNoticeDescription': { az: 'Vacib qeyd məzmunu', en: 'Important notice content', tr: 'Önemli not içeriği' },
  'terms.security': { az: 'Təhlükəsizlik', en: 'Security', tr: 'Güvenlik' },

  // Status (placeholders)
  'status.emailAnalysis': { az: 'Email Təhlili', en: 'Email Analysis', tr: 'E-posta Analizi' },
  'status.aiThreatDetection': { az: 'AI Təhdid Aşkarlanması', en: 'AI Threat Detection', tr: 'Yapay Zeka Tehdit Tespiti' },
  'status.osintIntegration': { az: 'OSINT İnteqrasiyası', en: 'OSINT Integration', tr: 'OSINT Entegrasyonu' },
  'status.apiService': { az: 'API Xidməti', en: 'API Service', tr: 'API Servisi' },
  'status.database': { az: 'Verilənlər Bazası', en: 'Database', tr: 'Veritabanı' },
  'status.notificationSystem': { az: 'Bildiriş Sistemi', en: 'Notification System', tr: 'Bildirim Sistemi' },
  'status.plannedMaintenance': { az: 'Planlaşdırılmış Texniki İşlər', en: 'Planned Maintenance', tr: 'Planlı Bakım' },
  'status.plannedMaintenanceDescription': { az: 'Planlaşdırılmış texniki işlər təsviri', en: 'Planned maintenance description', tr: 'Planlı bakım açıklaması' },
  'status.plannedMaintenanceDuration': { az: 'Planlaşdırılmış texniki işlər müddəti', en: 'Planned maintenance duration', tr: 'Planlı bakım süresi' },
  'status.operational': { az: 'Əməliyyat', en: 'Operational', tr: 'Çalışır' },
  'status.degraded': { az: 'Zəifləmiş', en: 'Degraded', tr: 'Azalmış' },
  'status.outage': { az: 'Kəsinti', en: 'Outage', tr: 'Kesinti' },
  'status.unknown': { az: 'Naməlum', en: 'Unknown', tr: 'Bilinmiyor' },
  'status.systemStatus': { az: 'Sistem Statusu', en: 'System Status', tr: 'Sistem Durumu' },
  'status.serviceStatus': { az: 'Xidmət Statusu', en: 'Service Status', tr: 'Servis Durumu' },
  'status.serviceStatusDescription': { az: 'Xidmət statusu təsviri', en: 'Service status description', tr: 'Servis durumu açıklaması' },
  'status.allSystemsOperational': { az: 'Bütün sistemlər işləkdir', en: 'All systems operational', tr: 'Tüm sistemler çalışıyor' },
  'status.allSystemsOperationalDescription': { az: 'Bütün sistemlər işləkdir təsviri', en: 'All systems operational description', tr: 'Tüm sistemler çalışıyor açıklaması' },
  'status.lastUpdated': { az: 'Son yeniləmə', en: 'Last updated', tr: 'Son güncelleme' },

  // Status (additional keys)
  'status.overallUptime': { az: 'Ümumi işlək vaxt', en: 'Overall Uptime', tr: 'Genel Çalışma Süresi' },
  'status.incidents': { az: 'Hadisələr', en: 'Incidents', tr: 'Olaylar' },
  'status.avgResponseTime': { az: 'Orta cavab vaxtı', en: 'Avg Response Time', tr: 'Ortalama Yanıt Süresi' },
  'status.serviceStatusDetailedDescription': { az: 'Xidmət statusunun ətraflı təsviri', en: 'Service status detailed description', tr: 'Servis durumu detaylı açıklama' },
  'status.uptime': { az: 'İşlək vaxt', en: 'Uptime', tr: 'Çalışma Süresi' },
  'status.responseTime': { az: 'Cavab vaxtı', en: 'Response Time', tr: 'Yanıt Süresi' },
  'status.recentIncidents': { az: 'Son hadisələr', en: 'Recent Incidents', tr: 'Son Olaylar' },
  'status.resolved': { az: 'Həll olundu', en: 'Resolved', tr: 'Çözüldü' },
  'status.noRecentIncidents': { az: 'Son hadisə yoxdur', en: 'No recent incidents', tr: 'Son olay yok' },
  'status.allServicesRunningNormally': { az: 'Bütün xidmətlər normal işləyir', en: 'All services running normally', tr: 'Tüm servisler normal çalışıyor' },
  'status.statusHistory': { az: 'Status tarixi', en: 'Status History', tr: 'Durum Geçmişi' },
  'status.systemPerformanceUptimeStatistics': { az: 'Sistem performansı və işlək vaxt statistikası', en: 'System performance & uptime statistics', tr: 'Sistem performansı ve çalışma süresi istatistikleri' },

  // Terms (additional keys)
  'terms.aiProtection': { az: 'AI qorunması', en: 'AI Protection', tr: 'Yapay Zeka Koruması' },
  'terms.reliability': { az: 'Etibarlılıq', en: 'Reliability', tr: 'Güvenilirlik' },
  'terms.uptime': { az: 'İşlək vaxt', en: 'Uptime', tr: 'Çalışma Süresi' },
  'terms.support': { az: 'Dəstək', en: 'Support', tr: 'Destek' },
  'terms.trialAndSubscription': { az: 'Sınaq və Abunəlik', en: 'Trial and Subscription', tr: 'Deneme ve Abonelik' },
  'terms.freeTrial': { az: 'Pulsuz sınaq', en: 'Free Trial', tr: 'Ücretsiz Deneme' },
  'terms.sevenDayTrial': { az: '7 günlük sınaq', en: '7-day trial', tr: '7 Günlük Deneme' },
  'terms.noCreditCard': { az: 'Kredit kartı tələb olunmur', en: 'No credit card required', tr: 'Kredi Kartı Gerekmez' },
  'terms.cancelAnytime': { az: 'İstənilən vaxt ləğv et', en: 'Cancel anytime', tr: 'İstediğin Zaman İptal Et' },
  'terms.fullFeatures': { az: 'Bütün funksiyalar', en: 'Full features', tr: 'Tüm Özellikler' },
  'terms.subscription': { az: 'Abunəlik', en: 'Subscription', tr: 'Abonelik' },
  'terms.autoRenewal': { az: 'Avtomatik yenilənmə', en: 'Auto-renewal', tr: 'Otomatik Yenileme' },
  'terms.guarantee': { az: 'Zəmanət', en: 'Guarantee', tr: 'Garanti' },
  'terms.changeAnytime': { az: 'İstənilən vaxt dəyiş', en: 'Change anytime', tr: 'İstediğin Zaman Değiştir' },
  'terms.moneyBack': { az: 'Pulun geri qaytarılması', en: 'Money-back', tr: 'Para İadesi' },
  'terms.prohibitedActivities': { az: 'Qadağan olunmuş fəaliyyətlər', en: 'Prohibited Activities', tr: 'Yasaklı Faaliyetler' },
  'terms.prohibitedActivitiesDescription': { az: 'Qadağan olunmuş fəaliyyətlərin təsviri', en: 'Prohibited activities description', tr: 'Yasaklı faaliyetlerin açıklaması' },
  'terms.illegalContent': { az: 'Qanunsuz məzmun', en: 'Illegal content', tr: 'Yasadışı İçerik' },
  'terms.serviceDisruption': { az: 'Xidmətin pozulması', en: 'Service disruption', tr: 'Servis Kesintisi' },
  'terms.accountSharing': { az: 'Hesab paylaşımı', en: 'Account sharing', tr: 'Hesap Paylaşımı' },
  'terms.automatedAttacks': { az: 'Avtomatlaşdırılmış hücumlar', en: 'Automated attacks', tr: 'Otomatik Saldırılar' },
  'terms.dataManipulation': { az: 'Məlumatların manipulyasiyası', en: 'Data manipulation', tr: 'Veri Manipülasyonu' },
  'terms.licenseViolation': { az: 'Lisenziya pozuntusu', en: 'License violation', tr: 'Lisans İhlali' },

  // About Page
  'about.title': { az: 'Haqqımızda', en: 'About Us', tr: 'Hakkımızda' },
  'about.futureOfEmailSecurity': { az: 'Email Təhlükəsizliyinin Gələcəyi', en: 'The Future of Email Security', tr: 'E-posta Güvenliğinin Geleceği' },
  'about.description': { az: 'PhishScope Pro, AI texnologiyası ilə email təhlükəsizliyini inqilab etdirən lider platformadır. Komandaların təhlükəli emailləri aşkarlamasına və qorunmasına kömək edirik.', en: 'PhishScope Pro is the leading platform revolutionizing email security with AI technology. We help teams detect and protect against malicious emails.', tr: 'PhishScope Pro, yapay zeka teknolojisiyle e-posta güvenliğinde devrim yaratan lider platformdur. Ekiplerin zararlı e-postaları tespit etmesine ve korunmasına yardımcı oluyoruz.' },
  'about.stats.emailsAnalyzed': { az: 'Analiz Edilmiş Email', en: 'Emails Analyzed', tr: 'Analiz Edilen E-posta' },
  'about.stats.accuracyRate': { az: 'Dəqiqlik Dərəcəsi', en: 'Accuracy Rate', tr: 'Doğruluk Oranı' },
  'about.stats.happyCustomers': { az: 'Məmnun Müştəri', en: 'Happy Customers', tr: 'Mutlu Müşteri' },
  'about.stats.support': { az: 'Dəstək', en: 'Support', tr: 'Destek' },
  'about.mission': { az: 'Missiyamız', en: 'Our Mission', tr: 'Misyonumuz' },
  'about.missionDescription': { az: 'Hər komandanın təhlükəsiz email mühitində işləməsi üçün güclü və istifadəçi dostu həllər təqdim etmək. AI texnologiyası ilə təhlükəli emailləri real vaxtda aşkarlayırıq və komandalarınızı qoruyuruq.', en: 'To provide powerful and user-friendly solutions for every team to work in a secure email environment. We detect malicious emails in real-time using AI technology and protect your teams.', tr: 'Her ekibin güvenli bir e-posta ortamında çalışabilmesi için güçlü ve kullanıcı dostu çözümler sunmak. Yapay zeka ile zararlı e-postaları gerçek zamanlı tespit ediyor ve ekiplerinizi koruyoruz.' },
  'about.watchDemo': { az: 'Demo İzlə', en: 'Watch Demo', tr: 'Demoyu İzle' },
  'about.contactUs': { az: 'Bizimlə Əlaqə', en: 'Contact Us', tr: 'Bize Ulaşın' },
  'about.secureEmail': { az: 'Təhlükəsiz Email', en: 'Secure Email', tr: 'Güvenli E-posta' },
  'about.aiThreatAnalysis': { az: 'AI təhlükə analizi', en: 'AI threat analysis', tr: 'Yapay Zeka Tehdit Analizi' },
  'about.realTimeAlerts': { az: 'Real-time bildirişlər', en: 'Real-time alerts', tr: 'Gerçek Zamanlı Uyarılar' },
  'about.osintIntegration': { az: 'OSINT inteqrasiyası', en: 'OSINT integration', tr: 'OSINT Entegrasyonu' },
  'about.ourValues': { az: 'Dəyərlərimiz', en: 'Our Values', tr: 'Değerlerimiz' },
  'about.corePrinciples': { az: 'Fəaliyyətimizi idarə edən əsas prinsiplər', en: 'The core principles that guide our work', tr: 'Çalışmalarımıza yön veren temel ilkeler' },
  'about.values.security': { az: 'Təhlükəsizlik', en: 'Security', tr: 'Güvenlik' },
  'about.values.securityDescription': { az: 'Məlumatlarınızın təhlükəsizliyi bizim ən yüksək prioritetimizdir', en: 'Your data security is our highest priority', tr: 'Veri güvenliğiniz en yüksek önceliğimizdir' },
  'about.values.accuracy': { az: 'Dəqiqlik', en: 'Accuracy', tr: 'Doğruluk' },
  'about.values.accuracyDescription': { az: '99.9% dəqiqlik dərəcəsi ilə təhlükəli emailləri aşkarlayırıq', en: 'We detect malicious emails with 99.9% accuracy', tr: 'Zararlı e-postaları %99,9 doğrulukla tespit ediyoruz' },
  'about.values.speed': { az: 'Sürət', en: 'Speed', tr: 'Hız' },
  'about.values.speedDescription': { az: 'Real-time analiz ilə dərhal nəticələr əldə edin', en: 'Get instant results with real-time analysis', tr: 'Gerçek zamanlı analiz ile anında sonuç alın' },
  'about.values.team': { az: 'Komanda', en: 'Team', tr: 'Ekip' },
  'about.values.teamDescription': { az: 'Komandanızın təhlükəsizliyini qoruyun və əməkdaşlıq edin', en: 'Protect your team and collaborate effectively', tr: 'Ekibinizi koruyun ve etkili iş birliği yapın' },
  'about.leadershipTeam': { az: 'Rəhbərlik Komandası', en: 'Leadership Team', tr: 'Liderlik Ekibi' },
  'about.experiencedProfessionals': { az: 'Təcrübəli mütəxəssislərdən ibarət komandamız', en: 'Our team of experienced professionals', tr: 'Deneyimli profesyonellerden oluşan ekibimiz' },
  'about.team.ceo.role': { az: 'Baş İcraçı Direktor', en: 'Chief Executive Officer', tr: 'Genel Müdür' },
  'about.team.ceo.bio': { az: '10+ illik təhlükəsizlik təcrübəsi ilə PhishScope Pro-nu qurdu. Əvvəllər böyük texnologiya şirkətlərində təhlükəsizlik məsləhətçisi olub.', en: 'Founded PhishScope Pro with 10+ years of security experience. Previously worked as a security consultant for major tech companies.', tr: "10+ yıllık güvenlik tecrübesiyle PhishScope Pro'yu kurdu. Daha önce büyük teknoloji şirketlerinde güvenlik danışmanı olarak çalıştı." },
  'about.team.cto.role': { az: 'Texnologiya Direktoru', en: 'Chief Technology Officer', tr: 'Teknoloji Direktörü' },
  'about.team.cto.bio': { az: 'AI və maşın öyrənmə sahəsində mütəxəssis. Stanford Universitetində kompüter elmləri təhsili alıb.', en: 'Expert in AI and machine learning. Studied computer science at Stanford University.', tr: "Yapay zeka ve makine öğrenimi konusunda uzman. Stanford Üniversitesi'nde bilgisayar bilimi okudu." },
  'about.team.cpo.role': { az: 'Məhsul Direktoru', en: 'Chief Product Officer', tr: 'Ürün Direktörü' },
  'about.team.cpo.bio': { az: 'İstifadəçi təcrübəsi və məhsul strategiyası sahəsində 8 il təcrübə. Əvvəllər Google və Microsoft-da işləyib.', en: '8 years of experience in user experience and product strategy. Previously worked at Google and Microsoft.', tr: "Kullanıcı deneyimi ve ürün stratejisi alanında 8 yıllık deneyim. Daha önce Google ve Microsoft'ta çalıştı." },
  'about.team.cso.role': { az: 'Təhlükəsizlik Direktoru', en: 'Chief Security Officer', tr: 'Güvenlik Direktörü' },
  'about.team.cso.bio': { az: 'Siber təhlükəsizlik sahəsində 12 il təcrübə. Əvvəllər həftəlik təhlükəsizlik araşdırmaları aparıb.', en: '12 years of experience in cybersecurity. Previously conducted weekly security research.', tr: 'Siber güvenlik alanında 12 yıllık deneyim. Daha önce haftalık güvenlik araştırmaları yaptı.' },
  'about.getInTouch': { az: 'Bizimlə Əlaqə Saxlayın', en: 'Get in Touch', tr: 'Bizimle İletişime Geçin' },
  'about.emailSecurityQuestions': { az: 'Email təhlükəsizliyi haqqında suallarınız varsa, komandamızla əlaqə saxlayın.', en: 'Have questions about email security? Get in touch with our team.', tr: 'E-posta güvenliği hakkında sorularınız varsa, ekibimizle iletişime geçin.' },
  'about.sendMessage': { az: 'Mesaj Göndər', en: 'Send Message', tr: 'Mesaj Gönder' },

  // Features Page
  'features.title': { az: 'Xüsusiyyətlər', en: 'Features', tr: 'Özellikler' },
  'features.powerfulCybersecurityTools': { az: 'Güclü Kibertəhlükəsizlik Alətləri', en: 'Powerful Cybersecurity Tools', tr: 'Güçlü Siber Güvenlik Araçları' },
  'features.everythingYouNeed': { az: 'PhishScope Pro ilə email təhdidlərini aşkar etmək, təhlil etmək və qarşısını almaq üçün lazım olan hər şey', en: 'Everything you need to detect, analyze, and prevent email threats with PhishScope Pro', tr: 'PhishScope Pro ile e-posta tehditlerini tespit etmek, analiz etmek ve önlemek için ihtiyacınız olan her şey' },
  'features.emailAnalysis': { az: 'Email Təhlili', en: 'Email Analysis', tr: 'E-posta Analizi' },
  'features.emailAnalysis.description': { az: 'EML, MSG və ham email məlumatlarını yükləyin və təhlil edin. Avtomatik IOC çıxarma və başlıq təhlili.', en: 'Upload and analyze .eml, .msg, and raw email data. Automatic IOC extraction and header analysis.', tr: 'EML, MSG ve ham e-posta verilerini yükleyin ve analiz edin. Otomatik IOC çıkarımı ve başlık analizi.' },
  'features.emailAnalysis.multipleFormatSupport': { az: 'Çoxlu format dəstəyi', en: 'Multiple format support', tr: 'Çoklu format desteği' },
  'features.emailAnalysis.automaticIOCextraction': { az: 'Avtomatik IOC çıxarma', en: 'Automatic IOC extraction', tr: 'Otomatik IOC çıkarımı' },
  'features.emailAnalysis.headerAnalysis': { az: 'Başlıq təhlili', en: 'Header analysis', tr: 'Başlık analizi' },
  'features.emailAnalysis.attachmentScanning': { az: 'Əlavə skanı', en: 'Attachment scanning', tr: 'Ek dosya taraması' },
  'features.authenticationValidation': { az: 'Autentifikasiya Yoxlaması', en: 'Authentication Validation', tr: 'Kimlik Doğrulama Doğrulaması' },
  'features.authenticationValidation.description': { az: 'SPF, DKIM və DMARC protokollarını yoxlayın. Təbii dil izahları ilə.', en: 'Validate SPF, DKIM, and DMARC protocols with natural language explanations.', tr: 'SPF, DKIM ve DMARC protokollerini doğrulayın. Doğal dil açıklamaları ile.' },
  'features.authenticationValidation.validation': { az: 'yoxlaması', en: 'validation', tr: 'doğrulama' },
  'features.authenticationValidation.signatureVerification': { az: 'imza təsdiqi', en: 'signature verification', tr: 'imza doğrulama' },
  'features.authenticationValidation.policyCheck': { az: 'siyasət yoxlaması', en: 'policy check', tr: 'politika kontrolü' },
  'features.authenticationValidation.naturalLanguageExplanations': { az: 'Təbii dil izahları', en: 'Natural language explanations', tr: 'Doğal dil açıklamaları' },
  'features.enrichment': { az: 'Zənginləşdirmə', en: 'Enrichment', tr: 'Zenginleştirme' },
  'features.enrichment.description': { az: 'IOC-ları müxtəlif təhdid kəşfiyyatı API-ləri ilə zənginləşdirin.', en: 'Enrich IOCs with multiple threat intelligence APIs.', tr: "IOC'leri çeşitli tehdit istihbarat API'leri ile zenginleştirin." },
  'features.enrichment.integration': { az: 'inteqrasiyası', en: 'integration', tr: 'entegrasyon' },
  'features.enrichment.scanning': { az: 'skanı', en: 'scanning', tr: 'tarama' },
  'features.enrichment.analysis': { az: 'təhlili', en: 'analysis', tr: 'analiz' },
  'features.enrichment.data': { az: 'məlumatları', en: 'data', tr: 'veri' },
  'features.threatAnalysis': { az: 'Təhdid Təhlili', en: 'Threat Analysis', tr: 'Tehdit Analizi' },
  'features.threatAnalysis.description': { az: 'GPT-4 ilə təhdid qiymətləndirməsi və MITRE ATT&CK xəritəsi.', en: 'GPT-4 powered threat assessment and MITRE ATT&CK mapping.', tr: 'GPT-4 destekli tehdit değerlendirmesi ve MITRE ATT&CK eşlemesi.' },
  'features.threatAnalysis.threatScoring': { az: 'Təhdid xalı', en: 'Threat scoring', tr: 'Tehdit puanlama' },
  'features.threatAnalysis.mapping': { az: 'xəritəsi', en: 'mapping', tr: 'eşleme' },
  'features.threatAnalysis.campaignAttribution': { az: 'Kampaniya atributu', en: 'Campaign attribution', tr: 'Kampanya ataması' },
  'features.threatAnalysis.automatedReporting': { az: 'Avtomatik hesabat', en: 'Automated reporting', tr: 'Otomatik raporlama' },
  'features.fastResults': { az: 'Sürətli Nəticələr', en: 'Fast Results', tr: 'Hızlı Sonuçlar' },
  'features.fastResults.description': { az: 'Saniyələr ərzində nəticələr alın, saatlar deyil.', en: 'Get results in seconds, not hours.', tr: 'Sonuçları saniyeler içinde alın, saatler değil.' },
  'features.fastResults.realTimeAnalysis': { az: 'Real vaxt təhlil', en: 'Real-time analysis', tr: 'Gerçek zamanlı analiz' },
  'features.fastResults.parallelProcessing': { az: 'Paralel emal', en: 'Parallel processing', tr: 'Paralel işleme' },
  'features.fastResults.cachingSystem': { az: 'Keş sistemi', en: 'Caching system', tr: 'Önbellek sistemi' },
  'features.fastResults.apiOptimization': { az: 'API optimallaşdırması', en: 'API optimization', tr: 'API optimizasyonu' },
  'features.teamCollaboration': { az: 'Komanda Əməkdaşlığı', en: 'Team Collaboration', tr: 'Ekip İşbirliği' },
  'features.teamCollaboration.description': { az: 'Hesabatları paylaşın və komanda ilə əməkdaşlıq edin.', en: 'Share reports and collaborate with your team.', tr: 'Raporları paylaşın ve ekibinizle iş birliği yapın.' },
  'features.teamCollaboration.sharedDashboard': { az: 'Paylaşılan dashboard', en: 'Shared dashboard', tr: 'Paylaşılan panel' },
  'features.teamCollaboration.roleBasedAccess': { az: 'Rol əsaslı giriş', en: 'Role-based access', tr: 'Rol tabanlı erişim' },
  'features.teamCollaboration.teamComments': { az: 'Komanda şərhləri', en: 'Team comments', tr: 'Ekip yorumları' },
  'features.teamCollaboration.auditTrail': { az: 'Audit izi', en: 'Audit trail', tr: 'Denetim izi' },
  'features.additionalCapabilities': { az: 'Əlavə İmkanlar', en: 'Additional Capabilities', tr: 'Ek Özellikler' },
  'features.otherPowerfulFeatures': { az: 'Platformamızın təklif etdiyi digər güclü xüsusiyyətlər', en: 'Other powerful features our platform offers', tr: 'Platformumuzun sunduğu diğer güçlü özellikler' },
  'features.globalThreatIntelligence': { az: 'Qlobal Təhdid Kəşfiyyatı', en: 'Global Threat Intelligence', tr: 'Küresel Tehdit İstihbaratı' },
  'features.globalThreatIntelligence.description': { az: 'Dünya miqyasında təhdid məlumatları bazası', en: 'Worldwide threat intelligence database', tr: 'Dünya çapında tehdit istihbarat veritabanı' },
  'features.enterpriseSecurity': { az: 'Müəssisə Təhlükəsizliyi', en: 'Enterprise Security', tr: 'Kurumsal Güvenlik' },
  'features.enterpriseSecurity.description': { az: 'SOC 2 Type II uyğunluğu və şifrələmə', en: 'SOC 2 Type II compliance and encryption', tr: 'SOC 2 Type II uyumluluğu ve şifreleme' },
  'features.analyticsDashboard': { az: 'Təhlil Paneli', en: 'Analytics Dashboard', tr: 'Analiz Paneli' },
  'features.analyticsDashboard.description': { az: 'Təhdid tendensiyaları və metrikalar', en: 'Threat trends and metrics', tr: 'Tehdit eğilimleri ve metrikler' },
  'features.automatedReports': { az: 'Avtomatik Hesabatlar', en: 'Automated Reports', tr: 'Otomatik Raporlar' },
  'features.automatedReports.description': { az: 'PDF, JSON və Markdown formatlarında', en: 'PDF, JSON, and Markdown formats', tr: 'PDF, JSON ve Markdown formatlarında' },
  'features.getStartedToday': { az: 'Bu gün başlayın', en: 'Get started today', tr: 'Bugün Başlayın' },
  'features.takeYourEmailSecurity': { az: 'PhishScope Pro ilə email təhlükəsizliyinizi növbəti səviyyəyə çıxarın', en: 'Take your email security to the next level with PhishScope Pro', tr: 'PhishScope Pro ile e-posta güvenliğinizi bir üst seviyeye taşıyın' },
  'features.startFreeTrial': { az: 'Pulsuz başla', en: 'Start Free Trial', tr: 'Ücretsiz Başla' },
  'features.contactSales': { az: 'Satış ilə əlaqə', en: 'Contact Sales', tr: 'Satış ile İletişim' },

  // Home Page
  'home.features.aiSecurityAnalysis': { az: 'AI Təhlükəsizlik Analizi', en: 'AI Security Analysis', tr: 'Yapay Zeka Güvenlik Analizi' },
  'home.features.aiSecurityAnalysisDescription': { az: 'Müasir AI texnologiyaları ilə phishing hücumlarını dəqiq müəyyən edin', en: 'Accurately detect phishing attacks with modern AI technology', tr: 'Modern yapay zeka teknolojisiyle phishing saldırılarını doğru şekilde tespit edin' },
  'home.features.realTimeSecurity': { az: 'Real-time Təhlükəsizlik', en: 'Real-time Security', tr: 'Gerçek Zamanlı Güvenlik' },
  'home.features.realTimeSecurityDescription': { az: 'Anlıq təhlükəsizlik təhlilləri və xəbərdarlıqlar', en: 'Instant security analysis and alerts', tr: 'Anında güvenlik analizi ve uyarılar' },
  'home.features.visibleSecurity': { az: 'Görünən Təhlükəsizlik', en: 'Visible Security', tr: 'Görünür Güvenlik' },
  'home.features.visibleSecurityDescription': { az: 'Təhlükəsizlik statusunuzu həmişə izləyin', en: 'Always monitor your security status', tr: 'Güvenlik durumunuzu her zaman izleyin' },
  'home.features.detailedReports': { az: 'Detallı Hesabatlar', en: 'Detailed Reports', tr: 'Detaylı Raporlar' },
  'home.features.detailedReportsDescription': { az: 'Təhlükəsizlik performansınız haqqında ətraflı məlumat', en: 'Detailed insights about your security performance', tr: 'Güvenlik performansınız hakkında detaylı bilgi' },
  'home.stats.accuracy': { az: 'Dəqiqlik', en: 'Accuracy', tr: 'Doğruluk' },
  'home.stats.emailsSecured': { az: 'Təhlükəsiz Email', en: 'Emails Secured', tr: 'Güvenli E-posta' },
  'home.stats.monitoring': { az: 'Monitorinq', en: 'Monitoring', tr: 'İzleme' },
  'home.stats.customers': { az: 'Müştəri', en: 'Customers', tr: 'Müşteri' },
  'home.testimonials.itDirector': { az: 'IT Direktoru', en: 'IT Director', tr: 'BT Direktörü' },
  'home.testimonials.aliMammadovContent': { az: 'PhishScope Pro bizim təhlükəsizlik strategiyamızı tamamilə dəyişdi. İndi daha təhlükəsizik.', en: 'PhishScope Pro completely transformed our security strategy. We feel much safer now.', tr: 'PhishScope Pro güvenlik stratejimizi tamamen değiştirdi. Artık çok daha güvendeyiz.' },
  'home.testimonials.securityConsultant': { az: 'Təhlükəsizlik Məsləhətçisi', en: 'Security Consultant', tr: 'Güvenlik Danışmanı' },
  'home.testimonials.sarahJohnsonContent': { az: 'Ən yaxşı phishing analiz platformu. Həqiqətən tövsiyə edirəm.', en: 'The best phishing analysis platform. Highly recommended.', tr: 'En iyi phishing analiz platformu. Kesinlikle tavsiye ederim.' },
  'home.testimonials.systemAdministrator': { az: 'Sistem Administratoru', en: 'System Administrator', tr: 'Sistem Yöneticisi' },
  'home.testimonials.maryamAliyevaContent': { az: 'İstifadəsi asan və çox effektiv. Komandamız üçün mükəmməl həll.', en: 'Easy to use and very effective. Perfect solution for our team.', tr: 'Kullanımı kolay ve çok etkili. Ekibimiz için mükemmel bir çözüm.' },
  'home.platform': { az: 'AI Təhlükəsizlik Platformu', en: 'AI Security Platform', tr: 'Yapay Zeka Güvenlik Platformu' },
  'home.accuracy': { az: '99.9% Dəqiqlik', en: '99.9% Accuracy', tr: '%99,9 Doğruluk' },
  'home.stopPhishing': { az: 'Phishing Hücumlarına', en: 'Stop Phishing', tr: 'Oltalama Saldırılarına' },
  'home.attacks': { az: 'Son Qoyun', en: 'Attacks', tr: 'Son Verin' },
  'home.secureEmail': { az: 'Müasir AI texnologiyaları ilə email təhlükəsizliyinizi təmin edin. Phishing hücumlarını real-time aşkarlayın və qarşısını alın.', en: 'Secure your email with modern AI technology. Detect and prevent phishing attacks in real-time.', tr: 'Modern yapay zeka ile e-posta güvenliğinizi sağlayın. Oltalama saldırılarını gerçek zamanlı tespit edin ve önleyin.' },
  'home.startFreeTrial': { az: 'Pulsuz Başlayın', en: 'Start Free Trial', tr: 'Ücretsiz Başlayın' },
  'home.watchDemo': { az: 'Demo İzləyin', en: 'Watch Demo', tr: 'Demoyu İzle' },
  'home.whyPhishScopePro': { az: 'Niyə PhishScope Pro?', en: 'Why PhishScope Pro?', tr: 'Neden PhishScope Pro?' },
  'home.whyPhishScopeProDescription': { az: 'Müasir təhlükəsizlik texnologiyaları ilə email təhlükəsizliyinizi təmin edin', en: 'Secure your email with cutting-edge security technology', tr: 'En yeni güvenlik teknolojileriyle e-posta güvenliğinizi sağlayın' },
  'home.whatOurCustomersSay': { az: 'Müştərilərimiz Nə Deyir?', en: 'What Our Customers Say?', tr: 'Müşterilerimiz Ne Diyor?' },
  'home.leadingCompaniesWorldwideTrustUs': { az: 'Dünyanın aparıcı şirkətləri bizə etibar edir', en: 'Leading companies worldwide trust us', tr: 'Dünyanın önde gelen şirketleri bize güveniyor' },
  'home.secureYourSecurity': { az: 'Təhlükəsizliyinizi Təmin Edin', en: 'Secure Your Security', tr: 'Güvenliğinizi Sağlayın' },
  'home.startNowAndTakeYourEmailSecurityToTheNextLevel': { az: 'İndi başlayın və email təhlükəsizliyinizi növbəti səviyyəyə qaldırın', en: 'Start now and take your email security to the next level', tr: 'Şimdi başlayın ve e-posta güvenliğinizi bir üst seviyeye taşıyın' },
  'home.contactSales': { az: 'Satışla əlaqə', en: 'Contact Sales', tr: 'Satış ile İletişim' },

  // Not Found Page
  'notfound.title': { az: 'Səhifə Tapılmadı', en: 'Page Not Found', tr: 'Sayfa Bulunamadı' },
  'notfound.underDevelopment': { az: 'Bu səhifə hələ də inkişaf mərhələsindədir', en: 'This page is still under development', tr: 'Bu sayfa hala geliştirme aşamasında' },
  'notfound.pageNotFound': { az: 'Axtardığınız səhifə hələ də yaradılır və ya mövcud deyil. Tezliklə burada yeni funksiyalar olacaq!', en: 'The page you\'re looking for is still being built or doesn\'t exist. New features will be here soon!', tr: 'Aradığınız sayfa henüz oluşturulmadı veya mevcut değil. Yakında burada yeni özellikler olacak!' },
  'notfound.tip': { az: '💡 Təklif: Ana səhifəyə qayıdın və mövcud funksiyalarımızı kəşf edin', en: '💡 Tip: Return to the homepage and explore our available features', tr: '💡 İpucu: Ana sayfaya dönün ve mevcut özelliklerimizi keşfedin' },
  'notfound.homepage': { az: 'Ana Səhifə', en: 'Homepage', tr: 'Ana Sayfa' },
  'notfound.watchDemo': { az: 'Demo İzlə', en: 'Watch Demo', tr: 'Demoyu İzle' },
  'notfound.popularPages': { az: 'Populyar səhifələr:', en: 'Popular pages:', tr: 'Popüler sayfalar:' },
  'notfound.pricing': { az: 'Qiymətlər', en: 'Pricing', tr: 'Fiyatlandırma' },
  'notfound.about': { az: 'Haqqımızda', en: 'About', tr: 'Hakkımızda' },
  'notfound.contact': { az: 'Əlaqə', en: 'Contact', tr: 'İletişim' },
  'notfound.features': { az: 'Funksiyalar', en: 'Features', tr: 'Özellikler' },
  'notfound.footerNote': { az: 'PhishScope Pro - Email təhlükəsizliyinin gələcəyi', en: 'PhishScope Pro - The future of email security', tr: 'PhishScope Pro - E-posta güvenliğinin geleceği' },

  // Contact Page
  'contact.contact': { en: 'Contact', az: 'Əlaqə', tr: 'İletişim' },
  'contact.get_in_touch': { en: 'Get in Touch', az: 'Bizimlə əlaqə', tr: 'Bizimle İletişime Geçin' },
  'contact.ready_to_help': { en: 'Have questions? Our team is ready to help you. 🚀', az: 'Suallarınız var? Komandamız sizə kömək etməyə hazırdır. 🚀', tr: 'Sorularınız mı var? Ekibimiz size yardımcı olmaya hazır. 🚀' },
  'contact.message_sent': { en: 'Message sent successfully! 🚀', az: 'Mesajınız göndərildi! 🚀', tr: 'Mesajınız başarıyla gönderildi! 🚀' },
  'contact.general_inquiries': { en: 'For general inquiries', az: 'Ümumi sorğular üçün', tr: 'Genel sorular için' },
  'contact.phone': { en: 'Phone', az: 'Telefon', tr: 'Telefon' },
  'contact.during_business_hours': { en: 'During business hours', az: 'İş saatlarında', tr: 'Mesai saatlarında' },
  'contact.address': { en: 'Address', az: 'Ünvan', tr: 'Adres' },
  'contact.headquarters': { en: 'Headquarters', az: 'Baş ofis', tr: 'Merkez ofis' },
  'contact.business_hours': { en: 'Business Hours', az: 'İş saatları', tr: 'Çalışma Saatleri' },
  'contact.monday_friday': { en: 'Monday - Friday', az: 'Bazar ertəsi - Cümə', tr: 'Pazartesi - Cuma' },
  'contact.sales_inquiry': { en: 'Sales inquiry', az: 'Satış sorğusu', tr: 'Satış talebi' },
  'contact.pricing_plans': { en: 'Pricing and plans', az: 'Qiymətlər və planlar', tr: 'Fiyatlandırma ve planlar' },
  'contact.technical_support': { en: 'Technical support', az: 'Texniki dəstək', tr: 'Teknik destek' },
  'contact.technical_issues': { en: 'Technical issues', az: 'Texniki problemlər', tr: 'Teknik sorunlar' },
  'contact.partnership': { en: 'Partnership', az: 'Tərəfdaşlıq', tr: 'Ortaklık' },
  'contact.business_partnership': { en: 'Business partnership', az: 'İş tərəfdaşlığı', tr: 'İş ortaklığı' },
  'contact.demo_request': { en: 'Demo request', az: 'Demo tələbi', tr: 'Demo talebi' },
  'contact.live_demo': { en: 'Live demo', az: 'Canlı demo', tr: 'Canlı demo' },
  'contact.other': { en: 'Other', az: 'Digər', tr: 'Diğer' },
  'contact.other_questions': { en: 'Other questions', az: 'Digər suallar', tr: 'Diğer sorular' },
  'contact.response_time': { en: 'Response Time', az: 'Cavab müddəti', tr: 'Yanıt Süresi' },
  'contact.satisfaction': { en: 'Satisfaction', az: 'Məmnuniyyət', tr: 'Memnuniyet' },
  'contact.customers': { en: 'Customers', az: 'Müştəri', tr: 'Müşteri' },
  'contact.support': { en: 'Support', az: 'Dəstək', tr: 'Destek' },
  'contact.send_us_a_message': { en: 'Send us a Message', az: 'Mesaj Göndərin', tr: 'Bize Mesaj Gönderin' },
  'contact.write_message_get_response': { en: 'Write your message and get a response quickly', az: 'Mesajınızı yazın və tezliklə cavab alacaqsınız', tr: 'Mesajınızı yazın ve hızlıca yanıt alın' },
  'contact.full_name': { en: 'Full Name', az: 'Ad Soyad', tr: 'Ad Soyad' },
  'contact.enter_your_name': { en: 'Enter your name', az: 'Adınızı daxil edin', tr: 'Adınızı girin' },
  'contact.email_address': { en: 'Email Address', az: 'Email ünvanı', tr: 'E-posta Adresi' },
  'contact.enter_your_email': { en: 'Enter your email', az: 'Email ünvanınızı daxil edin', tr: 'E-posta adresinizi girin' },
  'contact.company': { en: 'Company', az: 'Şirkət', tr: 'Şirket' },
  'contact.company_name': { en: 'Company name', az: 'Şirkət adı', tr: 'Şirket adı' },
  'contact.inquiry_type': { en: 'Inquiry Type', az: 'Sorğu Növü', tr: 'Talep Türü' },
  'contact.select': { en: 'Select', az: 'Seçin', tr: 'Seçin' },
  'contact.subject': { en: 'Subject', az: 'Mövzu', tr: 'Konu' },
  'contact.subject_of_message': { en: 'Subject of your message', az: 'Mesajınızın mövzusu', tr: 'Mesajınızın konusu' },
  'contact.message': { en: 'Message', az: 'Mesaj', tr: 'Mesaj' },
  'contact.write_your_message': { en: 'Write your message...', az: 'Mesajınızı yazın...', tr: 'Mesajınızı yazın...' },
  'contact.sending': { en: 'Sending...', az: 'Göndərilir...', tr: 'Gönderiliyor...' },
  'contact.send_message': { en: 'Send Message', az: 'Mesaj Göndər', tr: 'Mesaj Gönder' },
  'contact.quick_contact': { en: 'Quick Contact', az: 'Sürətli əlaqə', tr: 'Hızlı İletişim' },
  'contact.sales': { en: 'Sales', az: 'Satış', tr: 'Satış' },
  'contact.demo': { en: 'Demo', az: 'Demo', tr: 'Demo' },
  'contact.live_demo_request': { en: 'Live demo request', az: 'Canlı demo tələbi', tr: 'Canlı demo talebi' },
  'contact.frequently_asked_questions': { en: 'Frequently Asked Questions', az: 'Tez-tez Verilən Suallar', tr: 'Sıkça Sorulan Sorular' },
  'contact.what_is_response_time': { en: 'What is your response time?', az: 'Cavab vermə müddəti nə qədərdir?', tr: 'Yanıt süreniz nedir?' },
  'contact.general_inquiries_response': { en: 'We respond to general inquiries within 24 hours and sales inquiries within 4 hours.', az: 'Ümumi sorğulara 24 saat ərzində, satış sorğularına 4 saat ərzində cavab veririk.', tr: 'Genel sorulara 24 saat, satış taleplerine 4 saat içinde yanıt veriyoruz.' },
  'contact.can_i_request_demo': { en: 'Can I request a demo?', az: 'Demo tələb edə bilərəmmi?', tr: 'Demo talep edebilir miyim?' },
  'contact.sales_team_request': { en: 'Yes, you can request a live demo by contacting our sales team.', az: 'Bəli, satış komandamızla əlaqə saxlayaraq canlı demo tələb edə bilərsiniz.', tr: 'Evet, satış ekibimizle iletişime geçerek canlı demo talep edebilirsiniz.' },
  'contact.phone_support': { en: 'Do you offer phone support?', az: 'Telefon dəstəyi varmı?', tr: 'Telefon desteğiniz var mı?' },
  'contact.team_enterprise_plans': { en: 'We offer phone support for Team and Enterprise plans.', az: 'Team və Enterprise planları üçün telefon dəstəyi təklif edirik.', tr: 'Telefon desteği, Team ve Enterprise planları için sunulmaktadır.' },
  'contact.on_premise_deployment': { en: 'Is on-premise deployment available?', az: 'Yerində quraşdırma mümkündürmü?', tr: 'Yerinde kurulum mümkün mü?' },
  'contact.enterprise_customers': { en: 'On-premise deployment is available for Enterprise customers.', az: 'Enterprise müştərilər üçün yerində quraşdırma seçimi mövcuddur.', tr: 'Yerinde kurulum, Enterprise müşteriler için mevcuttur.' },
  'contact.enhance_email_security': { en: 'Enhance Your Email Security', az: 'Email Təhlükəsizliyinizi Təkmilləşdirin', tr: 'E-posta Güvenliğinizi Artırın' },
  'contact.protect_team_detect_malicious': { en: 'Protect your team and detect malicious emails with PhishScope Pro.', az: 'PhishScope Pro ilə komandanızı qoruyun və təhlükəli emailləri aşkarlayın.', tr: 'PhishScope Pro ile ekibinizi koruyun ve zararlı e-postaları tespit edin.' },
  'contact.watch_demo': { en: 'Watch Demo', az: 'Demo İzlə', tr: 'Demoyu İzle' },
  'contact.view_pricing': { en: 'View Pricing', az: 'Qiymətlər', tr: 'Fiyatları Gör' },

  'careers.health_insurance': { en: 'Health Insurance', az: 'Sağlamlıq Sığortası', tr: 'Sağlık Sigortası' },
  'careers.health_insurance_description': { en: 'Full health, dental, and vision coverage', az: 'Tam sağlamlıq, diş və göz sığortası', tr: 'Tam sağlık, diş ve göz sigortası' },
  'careers.flexible_hours': { en: 'Flexible Hours', az: 'Çevik İş Saatları', tr: 'Esnek Çalışma Saatları' },
  'careers.flexible_hours_description': { en: 'Flexible working hours for work-life balance', az: 'İş-həyat balansı üçün çevik iş saatları', tr: 'İş-yaşam dengesi için esnek çalışma saatları' },
  'careers.remote_work': { en: 'Remote Work', az: 'Uzaqdan İş', tr: 'Uzaktan Çalışma' },
  'careers.remote_work_description': { en: 'Full remote or hybrid work options', az: 'Tam uzaqdan və ya hibrid iş imkanları', tr: 'Tamamen uzaktan veya hibrit çalışma seçenekleri' },
  'careers.professional_growth': { en: 'Professional Growth', az: 'Peşəkar İnkişaf', tr: 'Profesyonel Gelişim' },
  'careers.professional_growth_description': { en: 'Training and certification programs', az: 'Təlim və sertifikat proqramları', tr: 'Eğitim ve sertifika programları' },
  'careers.team_culture': { en: 'Team Culture', az: 'Komanda Mədəniyyəti', tr: 'Takım Kültürü' },
  'careers.team_culture_description': { en: 'Inclusive and supportive work environment', az: 'İnklüziv və dəstəkləyici iş mühiti', tr: 'Kapsayıcı ve destekleyici çalışma ortamı' },
  'careers.engineering': { en: 'Engineering', az: 'Mühəndislik', tr: 'Mühendislik' },
  'careers.san_francisco_remote': { en: 'San Francisco / Remote', az: 'San Francisco / Uzaqdan', tr: 'San Francisco / Uzaktan' },
  'careers.full_time': { en: 'Full-time', az: 'Tam vaxt', tr: 'Tam zamanlı' },
  'careers.senior_security_engineer_description': { en: 'Develop email security systems and AI algorithms', az: 'Email təhlükəsizlik sistemləri və AI alqoritmlərinin inkişafı', tr: 'E-posta güvenlik sistemleri ve AI algoritmalarının geliştirilmesi' },
  'careers.product': { en: 'Product', az: 'Məhsul', tr: 'Ürün' },
  'careers.product_manager_description': { en: 'Lead product strategy and roadmap management', az: 'Məhsul strategiyası və roadmap idarəetməsi', tr: 'Ürün stratejisi ve yol haritası yönetimi' },
  'careers.remote': { en: 'Remote', az: 'Uzaqdan', tr: 'Uzaktan' },
  'careers.devops_engineer_description': { en: 'Manage cloud infrastructure and CI/CD pipelines', az: 'Cloud infrastrukturu və CI/CD pipeline-ların idarəetməsi', tr: 'Bulut altyapısı ve CI/CD süreçlerinin yönetimi' },
  'careers.sales': { en: 'Sales', az: 'Satış', tr: 'Satış' },
  'careers.sales_development_representative_description': { en: 'Identify and develop new customer opportunities', az: 'Yeni müştəri imkanlarının aşkarlanması və inkişafı', tr: 'Yeni müşteri fırsatlarını belirleme ve geliştirme' },
  'careers.design': { en: 'Design', az: 'Dizayn', tr: 'Tasarım' },
  'careers.ux_ui_designer_description': { en: 'Design user experience and interface', az: 'İstifadəçi təcrübəsi və interfeys dizaynı', tr: 'Kullanıcı deneyimi ve arayüz tasarımı' },
  'careers.customer_success': { en: 'Customer Success', az: 'Müştəri Uğuru', tr: 'Müşteri Başarısı' },
  'careers.customer_success_manager_description': { en: 'Ensure customer satisfaction and success', az: 'Müştəri məmnuniyyəti və uğurunun təmin edilməsi', tr: 'Müşteri memnuniyeti ve başarısını sağlamak' },
  'careers.careers': { en: 'Careers', az: 'Karyera', tr: 'Kariyer' },
  'careers.join_our_team': { en: 'Join Our Team', az: 'Bizimlə Qoşulun', tr: 'Ekibimize Katılın' },
  'careers.join_our_team_description': { en: 'We are looking for talented professionals to help build the future of cybersecurity', az: 'Kibertəhlükəsizliyin gələcəyini qurmaq üçün istedadlı mütəxəssislər axtarırıq', tr: 'Siber güvenliğin geleceğini inşa etmek için yetenekli profesyoneller arıyoruz' },
  'careers.why_phishscope_pro': { en: 'Why PhishScope Pro?', az: 'Niyə PhishScope Pro?', tr: 'Neden PhishScope Pro?' },
  'careers.why_phishscope_pro_description': { en: 'Work in an innovative environment and make a difference in cybersecurity', az: 'Innovativ mühitdə çalışın və kibertəhlükəsizlik sahəsində fərq yaradın', tr: 'Yenilikçi bir ortamda çalışın ve siber güvenlikte fark yaratın' },
  'careers.open_positions': { en: 'Open Positions', az: 'Açıq Vəzifələr', tr: 'Açık Pozisyonlar' },
  'careers.open_positions_description': { en: 'Find the right position for you and grow your career with us', az: 'Sizə uyğun vəzifəni tapın və karyeranızı bizimləbirgə inkişaf etdirin', tr: 'Size uygun pozisyonu bulun ve kariyerinizi bizimle geliştirin' },
  'careers.apply_now': { en: 'Apply Now', az: 'Müraciət et', tr: 'Hemen Başvur' },
  'careers.company_culture': { en: 'Company Culture', az: 'Şirkət Mədəniyyəti', tr: 'Şirket Kültürü' },
  'careers.company_culture_description': { en: 'We have built a culture that values diversity, inclusion, and innovation. We listen to everyone and value every contribution.', az: 'Biz müxtəliflik, inklüzivlik və innovasiyanı dəyərləndirən bir mədəniyyət qurmuşuq. Hər kəsin fikrini dinləyir və hər kəsin töhfəsini qiymətləndiririk.', tr: 'Çeşitliliği, kapsayıcılığı ve yeniliği değerli kılan bir kültür oluşturduk. Herkesin fikrine değer veriyor ve katkılarını önemsiyoruz.' },
  'careers.innovation': { en: 'Innovation', az: 'İnnovasiya', tr: 'Yenilik' },
  'careers.innovation_description': { en: 'We encourage testing new ideas and taking calculated risks', az: 'Yeni ideyaları sınaqdan keçirmək və riskləri götürmək üçün təşviq edirik', tr: 'Yeni fikirleri denemeye ve kontrollü riskler almaya teşvik ediyoruz' },
  'careers.collaboration': { en: 'Collaboration', az: 'Əməkdaşlıq', tr: 'İşbirliği' },
  'careers.collaboration_description': { en: 'We prioritize teamwork and open communication', az: 'Komanda işi və açıq ünsiyyəti prioritet edirik', tr: 'Takım çalışması ve açık iletişimi önceliklendiriyoruz' },
  'careers.growth': { en: 'Growth', az: 'İnkişaf', tr: 'Büyüme' },
  'careers.growth_description': { en: 'We support everyone professional and personal development', az: 'Hər kəsin peşəkar və şəxsi inkişafını dəstəkləyirik', tr: 'Herkesin profesyonel ve kişisel gelişimini destekliyoruz' },
  'careers.employees': { en: 'Employees', az: 'Əməkdaş', tr: 'Çalışan' },
  'careers.countries': { en: 'Countries', az: 'Ölkə', tr: 'Ülke' },
  'careers.dont_see_position': { en: "Don't see the position you're looking for?", az: 'Axtardığınız vəzifəni tapmadınız?', tr: 'Aradığınız pozisyonu bulamadınız mı?' },
  'careers.dont_see_position_description': { en: "We'd still love to hear from you! Send us your resume and learn about future opportunities.", az: 'Hələ də sizinlə tanış olmaq istəyirik! CV-nizi göndərin və gələcək imkanlar haqqında məlumat alın.', tr: 'Yine de sizinle tanışmak isteriz! Özgeçmişinizi gönderin ve gelecekteki fırsatları öğrenin.' },
  'careers.send_resume': { en: 'Send Resume', az: 'CV göndər', tr: 'Özgeçmiş Gönder' },
  'careers.learn_about_us': { en: 'Learn About Us', az: 'Şirkət haqqında', tr: 'Hakkımızda' },

  'blog.future_of_email_security_in_2024': { en: 'The Future of Email Security in 2024', az: '2024-də Email Təhlükəsizliyinin Gələcəyi', tr: '2024\'te E-posta Güvenliğinin Geleceği' },
  'blog.how_ai_technology_is_impacting_email_security_and_emerging_threats': { en: 'How AI technology is impacting email security and emerging threats.', az: 'AI texnologiyasının email təhlükəsizliyinə təsiri və yeni təhdidlər haqqında.', tr: 'Yapay zeka teknolojisinin e-posta güvenliğine ve yeni tehditlere etkisi.' },
  'blog.5_minutes_read': { en: '5 min read', az: '5 dəqiqə', tr: '5 dk okuma' },
  'blog.security': { en: 'Security', az: 'Təhlükəsizlik', tr: 'Güvenlik' },
  'blog.10_tips_to_detect_phishing_attacks': { en: '10 Tips to Detect Phishing Attacks', az: 'Phishing Hücumlarını Aşkarlamaq üçün 10 Təklif', tr: 'Oltalama Saldırılarını Tespit Etmek için 10 İpucu' },
  'blog.practical_advice_to_protect_your_team_from_phishing_attacks': { en: 'Practical advice to protect your team from phishing attacks.', az: 'Komandanızı phishing hücumlarından qorumaq üçün praktik məsləhətlər.', tr: 'Ekibinizi oltalama saldırılarından korumak için pratik öneriler.' },
  'blog.8_minutes_read': { en: '8 min read', az: '8 dəqiqə', tr: '8 dk okuma' },
  'blog.training': { en: 'Training', az: 'Təlim', tr: 'Eğitim' },
  'blog.osint_and_email_analysis': { en: 'OSINT and Email Analysis', az: 'OSINT və Email Analizi', tr: 'OSINT ve E-posta Analizi' },
  'blog.using_open_source_intelligence_to_detect_email_threats': { en: 'Using open-source intelligence to detect email threats.', az: 'Açıq mənbəli kəşfiyyat məlumatlarından istifadə edərək email təhlükələrini aşkarlamaq.', tr: 'Açıq kaynak istihbaratı kullanarak e-posta tehditlerini tespit etmek.' },
  'blog.12_minutes_read': { en: '12 min read', az: '12 dəqiqə', tr: '12 dk okuma' },
  'blog.technology': { en: 'Technology', az: 'Texnologiya', tr: 'Teknoloji' },
  'blog.blog': { en: 'Blog', az: 'Blog', tr: 'Blog' },
  'blog.security_insights': { en: 'Security Insights', az: 'Təhlükəsizlik Məlumatları', tr: 'Güvenlik İçgörüleri' },
  'blog.latest_insights_on_email_security_phishing_detection_and_cybersecurity': { en: 'Latest insights on email security, phishing detection, and cybersecurity.', az: 'Email təhlükəsizliyi, phishing aşkarlama və kibertəhlükəsizlik haqqında ən son məlumatlar.', tr: 'E-posta güvenliği, oltalama tespiti ve siber güvenlik hakkında en son bilgiler.' },
  'blog.read': { en: 'Read', az: 'Oxu', tr: 'Oku' },
  'blog.more_content_coming': { en: 'More Content Coming', az: 'Daha Çox Məzmun Gəlir', tr: 'Daha Fazla İçerik Geliyor' },
  'blog.we_ll_be_adding_more_security_articles_and_training_materials_soon': { en: "We'll be adding more security articles and training materials soon.", az: 'Tezliklə daha çox təhlükəsizlik məqalələri və təlim materialları əlavə edəcəyik.', tr: 'Yakında daha fazla güvenlik makalesi ve eğitim materyali ekleyeceğiz.' },
};

export const getLocale = (): 'az' | 'en' | 'tr' => {
  if (typeof window === 'undefined') return 'en';
  
  // Check localStorage first
  const stored = localStorage.getItem('locale');
  if (stored === 'az' || stored === 'en' || stored === 'tr') return stored as 'az' | 'en' | 'tr';
  
  // Check browser locale
  const browserLocale = navigator.language.toLowerCase();
  if (browserLocale.startsWith('az')) return 'az';
  if (browserLocale.startsWith('tr')) return 'tr';
  
  // Check geolocation (would need IP-based detection in real app)
  // For now, default to English
  return 'en';
};

export const setLocale = (locale: 'az' | 'en' | 'tr') => {
  localStorage.setItem('locale', locale);
  window.dispatchEvent(new Event('locale-change'));
};

export const t = (key: string, locale?: 'az' | 'en' | 'tr'): string => {
  const currentLocale = locale || getLocale();
  return translations[key]?.[currentLocale] || key;
};